#!/usr/bin/env php
<?php
ini_set('display_errors', '0');
ini_set('display_startup_errors', '0');
error_reporting(E_ERROR | E_PARSE);

require __DIR__ . '/bootstrap/app.php';

// Legge il valore dalla variabile d'ambiente o usa 1 come default
$sleepTime = (int)($_ENV['WORKER_SLEEP_TIME'] ?? 1);

$queueService = $container->get(\Mlab\Webhook\Services\QueueService::class);

echo date('Y-m-d H:i:s') . " - Worker webhook avviato...\n";

while (true) {
    $queueService->processQueue();
    echo date('Y-m-d H:i:s') . " - Elaborazione completata\n";
    sleep($sleepTime);
}